### ISSUE TITLE
Problems trying to use the Recharts example

### ISSUE THREAD

**Issue by vasily-kirichenko** [fable-compiler/fableconf-workshops#3]
1. `applySpread` is depricated without tips what function should be used instead:

![image](https://user-images.githubusercontent.com/873919/34452618-0022b3b8-ed54-11e7-9ffa-437295339c57.png)

2. `createEl` just disappered:

![image](https://user-images.githubusercontent.com/873919/34452582-b31d56fe-ed53-11e7-9f2e-3af29379dafe.png)

I use `createElement` instead, no idea if it's correct.

3. It's compiled, but throws exception at runtime:

![image](https://user-images.githubusercontent.com/873919/34452626-3095c01c-ed54-11e7-9eae-df1f452d899d.png)

![image](https://user-images.githubusercontent.com/873919/34452630-45cc4cb2-ed54-11e7-8751-a1c0ed49b4c6.png)

**Comment by vasily-kirichenko** [comment]
I found this ts binding https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/recharts and tried to convert it with `ts2fable`. The resulting code does not compile :(

![image](https://user-images.githubusercontent.com/873919/34452742-39987b0c-ed57-11e7-9594-fe469a1a572e.png)

![image](https://user-images.githubusercontent.com/873919/34452743-43556f60-ed57-11e7-94d4-53e4ca9c2044.png)

**Comment by alfonsogarciacaro** [comment]
Sorry for the confusion, this was done after getting some feedback at FableConf that `applySpread` was confusing, so now you only need to use [createElement](https://github.com/fable-compiler/fable-react/blob/3ec8497d5984cbe917a87a81d63b1fa266e59e8f/src/Fable.Recharts/Fable.Recharts.fs#L178). I have fixed it and published `Fable.Recharts` in Nuget. You can use that or just copy [the source](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.Recharts/Fable.Recharts.fs) (a single file atm).

Unfortunately the bindings are not complete. When I started them for some reason I didn't use the TS declaration. I wrote them based on [Recharts documentation](http://recharts.org/#/en-US/api).

**Comment by vasily-kirichenko** [comment]
Thanks, it works!

![1](https://user-images.githubusercontent.com/873919/34460519-eaf7237e-ee21-11e7-94a1-4f0d59274c36.gif)

**Comment by alfonsogarciacaro** [comment]
@vasily-kirichenko I've published an (hopefully) almost complete version of the Recharts bindings. I changed a couple of things, mainly adding `RequireQualifiedAccess` to Props to prevent conflicts. Can you please have a look and give your feedback? You can find usage samples here: https://github.com/fable-compiler/fable-react/tree/f53ee84bc660bcfa1e676934814a6c93df1a4155/src/Fable.Recharts.Sample
